### ISSUE TITLE
Current plan

### ISSUE THREAD

**Issue by ankush** [frappe/backport#2]
## TODO

- [ ] Cleanup JS code from VCS. Typescript should be either dynamically compiled or some other way to keep JS code out of VCS.
- [ ] Allow merge/rebase merges to be backported.
- [x] Forcefully backport conflicting PRs and leave conflict markers for authors to resolve.   https://github.com/frappe/backport/pull/4

**Comment by ankush** [comment]
We just use mergify now
